### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'get' in add_response  (SearchModule.py)

### ISSUE THREAD

**Issue by CrimsonGlory** [codexgigassys/codex-backend#105]
ESC[32mapi_1                |ESC[0m Traceback (most recent call last):
ESC[32mapi_1                |ESC[0m   File "/usr/local/lib/python2.7/site-packages/bottle.py", line 862, in _handle
ESC[32mapi_1                |ESC[0m     return route.call(**args)
ESC[32mapi_1                |ESC[0m   File "/usr/local/lib/python2.7/site-packages/bottle.py", line 1740, in wrapper
ESC[32mapi_1                |ESC[0m     rv = callback(*a, **ka)
ESC[32mapi_1                |ESC[0m   File "/myapp/src/api2.py", line 206, in search
datetime.datetime(2017, 1, 24, 13, 20, 18, 602000), u'daily': 1509, u'b
ESC[32mapi_1                |ESC[0m     res=SearchModule.search_by_id(data,limit,columns,True)
ESC[32mapi_1                |ESC[0m   File "/myapp/src/SearchModule.py", line 208, in search_by_id
ESC[32mapi_1                |ESC[0m     sha1=add_response.get('hash')
ESC[32mapi_1                |ESC[0m AttributeError: 'NoneType' object has no attribute 'get'
ESC[32mapi_1                |ESC[0m 192.168.0.92 - - [2017-01-22 03:13:43] "GET /api/v1/search?data=1%3Dd3c81a7204cec2d34a99e64b671ec63b&limit=1 HTTP/1
ESC[32mapi_1                |ESC[0m []

**Comment by CrimsonGlory** [comment]
Can't reproduce. Probably a bug before the last virusTotalApi.py was deployed on the server.
