### ISSUE TITLE
 ERROR:root:Error parsing pefileModule with sample ...

### ISSUE THREAD

**Issue by CrimsonGlory** [codexgigassys/codex-backend#110]
2017-02-01T07:01:06+00:00 172.21.0.1 api[953]: ERROR:root:Error parsing pefileModule with sample:83891e3dc8cb1ad7322cdc53fbac92ae53fa881a
2017-02-01T07:01:06+00:00 172.21.0.1 api[953]: Traceback (most recent call last):
2017-02-01T07:01:06+00:00 172.21.0.1 api[953]:   File "/myapp/src/Modules/PEFileModule.py", line 27, in initialize
2017-02-01T07:01:06+00:00 172.21.0.1 api[953]:     pefile.DIRECTORY_ENTRY['IMAGE_DIRECTORY_ENTRY_RESOURCE']])
2017-02-01T07:01:06+00:00 172.21.0.1 api[953]:   File "/usr/local/lib/python2.7/site-packages/pefile.py", line 2370, in parse_data_directories
2017-02-01T07:01:06+00:00 172.21.0.1 api[953]:     value = entry[1](dir_entry.VirtualAddress, dir_entry.Size)
2017-02-01T07:01:06+00:00 172.21.0.1 api[953]:   File "/usr/local/lib/python2.7/site-packages/pefile.py", line 2929, in parse_resources_directory
2017-02-01T07:01:06+00:00 172.21.0.1 api[953]:     string_entry_data = self.get_data(string_entry_rva, string_entry_size)
2017-02-01T07:01:06+00:00 172.21.0.1 api[953]:   File "/usr/local/lib/python2.7/site-packages/pefile.py", line 4116, in get_data
2017-02-01T07:01:06+00:00 172.21.0.1 api[953]:     raise PEFormatError('data at RVA can\'t be fetched. Corrupt header?')
2017-02-01T07:01:06+00:00 172.21.0.1 api[953]: PEFormatError: "data at RVA can't be fetched. Corrupt header?"
--
2017-02-01T07:02:05+00:00 172.21.0.1 api[953]: ERROR:root:Error parsing pefileModule with sample:27d121ed2462f485dc47c34fc6e08afdfaad5004
2017-02-01T07:02:05+00:00 172.21.0.1 api[953]: Traceback (most recent call last):
2017-02-01T07:02:05+00:00 172.21.0.1 api[953]:   File "/myapp/src/Modules/PEFileModule.py", line 27, in initialize
2017-02-01T07:02:05+00:00 172.21.0.1 api[953]:     pefile.DIRECTORY_ENTRY['IMAGE_DIRECTORY_ENTRY_RESOURCE']])
2017-02-01T07:02:05+00:00 172.21.0.1 api[953]:   File "/usr/local/lib/python2.7/site-packages/pefile.py", line 2370, in parse_data_directories
2017-02-01T07:02:05+00:00 172.21.0.1 api[953]:     value = entry[1](dir_entry.VirtualAddress, dir_entry.Size)
2017-02-01T07:02:05+00:00 172.21.0.1 api[953]:   File "/usr/local/lib/python2.7/site-packages/pefile.py", line 2929, in parse_resources_directory
2017-02-01T07:02:05+00:00 172.21.0.1 api[953]:     string_entry_data = self.get_data(string_entry_rva, string_entry_size)
2017-02-01T07:02:05+00:00 172.21.0.1 api[953]:   File "/usr/local/lib/python2.7/site-packages/pefile.py", line 4116, in get_data
2017-02-01T07:02:05+00:00 172.21.0.1 api[953]:     raise PEFormatError('data at RVA can\'t be fetched. Corrupt header?')
2017-02-01T07:02:05+00:00 172.21.0.1 api[953]: PEFormatError: "data at RVA can't be fetched. Corrupt header?"
--
2017-02-01T08:05:53+00:00 172.21.0.1 api[953]: ERROR:root:Error parsing pefileModule with sample:5dff73542fb6e0997d1926289b3d4c3496d010d8
2017-02-01T08:05:53+00:00 172.21.0.1 api[953]: Traceback (most recent call last):
2017-02-01T08:05:53+00:00 172.21.0.1 api[953]:   File "/myapp/src/Modules/PEFileModule.py", line 27, in initialize
2017-02-01T08:05:53+00:00 172.21.0.1 api[953]:     pefile.DIRECTORY_ENTRY['IMAGE_DIRECTORY_ENTRY_RESOURCE']])
2017-02-01T08:05:53+00:00 172.21.0.1 api[953]:   File "/usr/local/lib/python2.7/site-packages/pefile.py", line 2370, in parse_data_directories
2017-02-01T08:05:53+00:00 172.21.0.1 api[953]:     value = entry[1](dir_entry.VirtualAddress, dir_entry.Size)
2017-02-01T08:05:53+00:00 172.21.0.1 api[953]:   File "/usr/local/lib/python2.7/site-packages/pefile.py", line 2929, in parse_resources_directory
2017-02-01T08:05:53+00:00 172.21.0.1 api[953]:     string_entry_data = self.get_data(string_entry_rva, string_entry_size)
2017-02-01T08:05:53+00:00 172.21.0.1 api[953]:   File "/usr/local/lib/python2.7/site-packages/pefile.py", line 4116, in get_data
2017-02-01T08:05:53+00:00 172.21.0.1 api[953]:     raise PEFormatError('data at RVA can\'t be fetched. Corrupt header?')
2017-02-01T08:05:53+00:00 172.21.0.1 api[953]: PEFormatError: "data at RVA can't be fetched. Corrupt header?"

**Comment by CrimsonGlory** [comment]
Same error, other hash
ERROR:root:Error parsing pefileModule with sample:4d568c14bfe74d0a6ebb8a2706ea1e5e96377604
